-- ============================================
-- BUSINESS PERFORMANCE INTELLIGENCE DASHBOARD
-- Oracle Database 21c
-- ============================================

-- CUSTOMERS
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150),
    city VARCHAR2(50),
    region VARCHAR2(50),
    customer_type VARCHAR2(30),
    registration_date DATE
);

-- PRODUCTS
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    unit_price NUMBER(10,2),
    cost_price NUMBER(10,2)
);

-- ORDERS
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    order_date DATE NOT NULL,
    order_status VARCHAR2(30),
    payment_method VARCHAR2(30),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

-- ORDER ITEMS
CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

-- INDEXES
CREATE INDEX idx_orders_date
ON orders(order_date);

CREATE INDEX idx_orders_customer
ON orders(customer_id);

CREATE INDEX idx_items_product
ON order_items(product_id);

-- VERIFY
SELECT table_name
FROM user_tables
WHERE table_name IN (
    'CUSTOMERS',
    'PRODUCTS',
    'ORDERS',
    'ORDER_ITEMS'
)
ORDER BY table_name;